stages:
  - test
  - build

test_bot:
  stage: test
  image: node:22
  script:
    - cd ./bot/
    - npm install
    - npm test
  only:
    changes:
      - .gitlab-ci.yml
      - bot/**/*

build_bot:
  stage: build
  image: docker:cli
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd ./bot/
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  only:
    changes:
      - .gitlab-ci.yml
      - bot/**/*

deploy_bot_via_webhook:
  stage: deploy
  image: alpine:3
  script:
    - apk add --no-cache curl
    - curl -X POST $PORTAINER_WEBHOOK

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
